# Generated by Django 6.0.2 on 2026-07-12 23:12

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='SucursalCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True)),
                ('tipo', models.CharField(choices=[('sucursal', 'Sucursal'), ('cliente_mayorista', 'Cliente mayorista')], max_length=24)),
                ('activa', models.BooleanField(default=True)),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perfil_pedidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sucursal/cliente',
                'verbose_name_plural': 'Sucursales/clientes',
                'ordering': ['tipo', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_nombre', models.CharField(max_length=150)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_confirmacion', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmado', 'Confirmado'), ('enviado', 'Enviado'), ('recibido', 'Recibido')], default='pendiente', max_length=16)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('eliminado', models.BooleanField(default=False)),
                ('sucursal_cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='pedidos.sucursalcliente')),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=3, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.001')), django.core.validators.MaxValueValidator(Decimal('999.999'))])),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=6)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pedidos.pedido')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items_pedido', to='pedidos.producto')),
            ],
            options={
                'ordering': ['producto__orden'],
                'constraints': [models.UniqueConstraint(fields=('pedido', 'producto'), name='item_unico_por_producto_en_pedido')],
            },
        ),
        migrations.CreateModel(
            name='Precio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=6)),
                ('fecha_vigencia', models.DateField(default=django.utils.timezone.localdate)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios', to='pedidos.producto')),
                ('sucursal_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios', to='pedidos.sucursalcliente')),
            ],
            options={
                'ordering': ['producto__orden', '-fecha_vigencia'],
                'constraints': [models.UniqueConstraint(fields=('producto', 'sucursal_cliente', 'fecha_vigencia'), name='precio_unico_por_fecha')],
            },
        ),
    ]
