# Generated by Django 5.2.16 on 2026-07-15 01:47

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_producto_nombre_ticket_activo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_inicio_pedidos', models.TimeField(default=datetime.time(8, 0), help_text='Hora a partir de la cual se aceptan pedidos.')),
                ('hora_fin_pedidos', models.TimeField(default=datetime.time(16, 0), help_text='Hora hasta la cual se aceptan pedidos.')),
                ('hora_envio_recordatorio', models.TimeField(default=datetime.time(14, 0), help_text='Hora a la que se envía el recordatorio diario de pedidos.')),
                ('dias_recordatorio', models.CharField(default='1,2,3,4,5', help_text='Días ISO (1=lunes ... 7=domingo) separados por coma en que se envía el recordatorio.', max_length=20)),
                ('email_remitente', models.CharField(blank=True, help_text='Nombre visible del remitente, ej. "Los Tocayos <tocayos.tacos@gmail.com>". Si se deja vacío se usa DEFAULT_FROM_EMAIL/EMAIL_HOST_USER.', max_length=255)),
                ('recordatorios_habilitados', models.BooleanField(default=True, help_text='Habilitar o deshabilitar el envío de recordatorios diarios.')),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('actualizado_por', models.CharField(blank=True, max_length=150)),
            ],
            options={
                'verbose_name': 'Configuración',
                'verbose_name_plural': 'Configuración del sistema',
            },
        ),
        migrations.AddField(
            model_name='sucursalcliente',
            name='email',
            field=models.EmailField(blank=True, help_text='Correo al que se envía el recordatorio diario de pedidos.', max_length=254),
        ),
        migrations.CreateModel(
            name='LogRecordatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('enviado', 'Enviado exitosamente'), ('error', 'Error al enviar'), ('saltado', 'Saltado (sin correo)')], max_length=16)),
                ('mensaje_error', models.TextField(blank=True)),
                ('sucursal_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs_recordatorio', to='pedidos.sucursalcliente')),
            ],
            options={
                'verbose_name': 'Log de recordatorio',
                'verbose_name_plural': 'Logs de recordatorios',
                'ordering': ['-fecha_envio'],
            },
        ),
    ]
