# Generated by Django 6.0.8 on 2026-08-12 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0009_precio_vigente_idx'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='promo_aguilas_martes',
        ),
    ]
