# Generated by Django 6.0.7 on 2026-08-15 17:33

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models
from django.utils import timezone


ESTADOS_ACTIVOS = ("confirmado", "enviado", "recibido")


def agrupar_pedidos_existentes(apps, schema_editor):
    Pedido = apps.get_model("pedidos", "Pedido")
    MacroPedido = apps.get_model("pedidos", "MacroPedido")
    grupos = {}

    pedidos = Pedido.objects.filter(
        estado__in=ESTADOS_ACTIVOS,
        fecha_confirmacion__isnull=False,
    ).order_by("sucursal_cliente_id", "fecha_confirmacion", "id")

    for pedido in pedidos.iterator():
        fecha_local = timezone.localtime(pedido.fecha_confirmacion).date()
        clave = (pedido.sucursal_cliente_id, fecha_local)
        grupo = grupos.setdefault(
            clave,
            {
                "pedidos": [],
                "total": Decimal("0.00"),
                "ultima": pedido.fecha_confirmacion,
                "ultima_activa": None,
                "estados": set(),
                "todos_eliminados": True,
            },
        )
        grupo["pedidos"].append(pedido.id)
        grupo["ultima"] = max(grupo["ultima"], pedido.fecha_confirmacion)
        if not pedido.eliminado:
            grupo["total"] += pedido.total
            grupo["estados"].add(pedido.estado)
            grupo["ultima_activa"] = max(
                filter(None, (grupo["ultima_activa"], pedido.fecha_confirmacion))
            )
            grupo["todos_eliminados"] = False

    for (sucursal_id, fecha_local), grupo in grupos.items():
        if "confirmado" in grupo["estados"]:
            estado = "confirmado"
        elif "enviado" in grupo["estados"]:
            estado = "enviado"
        else:
            estado = "recibido"

        macro = MacroPedido.objects.create(
            sucursal_cliente_id=sucursal_id,
            fecha_pedido=fecha_local,
            ultima_confirmacion=grupo["ultima_activa"] or grupo["ultima"],
            estado=estado,
            total=grupo["total"],
            eliminado=grupo["todos_eliminados"],
        )
        Pedido.objects.filter(id__in=grupo["pedidos"]).update(macropedido_id=macro.id)


def desagrupar_pedidos(apps, schema_editor):
    Pedido = apps.get_model("pedidos", "Pedido")
    MacroPedido = apps.get_model("pedidos", "MacroPedido")
    Pedido.objects.update(macropedido_id=None)
    MacroPedido.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0010_elimina_promo_aguilas_martes'),
    ]

    operations = [
        migrations.CreateModel(
            name='MacroPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_publico', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('fecha_pedido', models.DateField(db_index=True)),
                ('ultima_confirmacion', models.DateTimeField()),
                ('estado', models.CharField(choices=[('confirmado', 'Confirmado'), ('enviado', 'Enviado'), ('recibido', 'Recibido')], default='confirmado', max_length=16)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('eliminado', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('sucursal_cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='macropedidos', to='pedidos.sucursalcliente')),
            ],
            options={
                'ordering': ['-fecha_pedido', '-ultima_confirmacion'],
            },
        ),
        migrations.AddField(
            model_name='pedido',
            name='macropedido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='pedidos.macropedido'),
        ),
        migrations.RunPython(agrupar_pedidos_existentes, desagrupar_pedidos),
        migrations.AddIndex(
            model_name='macropedido',
            index=models.Index(fields=['sucursal_cliente', '-fecha_pedido'], name='macro_sucursal_fecha_idx'),
        ),
        migrations.AddConstraint(
            model_name='macropedido',
            constraint=models.UniqueConstraint(fields=('sucursal_cliente', 'fecha_pedido'), name='macropedido_unico_por_sucursal_dia'),
        ),
    ]
