# Generated by Django 6.0.7 on 2026-08-19 16:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models
from django.db.models import Count, Sum


def consolidar_pedidos_pendientes_duplicados(apps, schema_editor):
    Pedido = apps.get_model('pedidos', 'Pedido')
    ItemPedido = apps.get_model('pedidos', 'ItemPedido')
    if schema_editor.connection.vendor == 'postgresql':
        tabla = schema_editor.quote_name(Pedido._meta.db_table)
        schema_editor.execute(f'LOCK TABLE {tabla} IN SHARE ROW EXCLUSIVE MODE')
    duplicados = (
        Pedido.objects.filter(estado='pendiente', eliminado=False)
        .values('sucursal_cliente_id')
        .annotate(cantidad=Count('id'))
        .filter(cantidad__gt=1)
    )
    for grupo in duplicados.iterator():
        pedidos = list(
            Pedido.objects.filter(
                sucursal_cliente_id=grupo['sucursal_cliente_id'],
                estado='pendiente',
                eliminado=False,
            ).order_by('-fecha_creacion', '-id')
        )
        conservado = pedidos[0]
        productos_conservados = set(
            ItemPedido.objects.filter(pedido_id=conservado.id).values_list(
                'producto_id', flat=True
            )
        )
        for obsoleto in pedidos[1:]:
            for item in ItemPedido.objects.filter(pedido_id=obsoleto.id).order_by('id'):
                if item.producto_id not in productos_conservados:
                    item.pedido_id = conservado.id
                    item.save(update_fields=['pedido'])
                    productos_conservados.add(item.producto_id)
            obsoleto.eliminado = True
            obsoleto.save(update_fields=['eliminado'])

        total = ItemPedido.objects.filter(pedido_id=conservado.id).aggregate(
            total=Sum('subtotal')
        )['total'] or 0
        conservado.total = total
        conservado.save(update_fields=['total'])


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0011_macropedidos_diarios'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('evento', models.CharField(db_index=True, max_length=80)),
                ('intento_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('dispositivo_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('sesion_hash', models.CharField(blank=True, max_length=16)),
                ('ocurrido_en', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('recibido_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('detalle', models.JSONField(blank=True, default=dict)),
                ('user_agent', models.CharField(blank=True, max_length=300)),
                ('direccion_ip', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Evento de cliente',
                'verbose_name_plural': 'Eventos de cliente',
                'ordering': ['-recibido_en'],
            },
        ),
        migrations.CreateModel(
            name='SesionActiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(editable=False, max_length=64, unique=True)),
                ('dispositivo_id', models.CharField(blank=True, max_length=64)),
                ('dispositivo', models.CharField(blank=True, max_length=200)),
                ('direccion_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('iniciada_en', models.DateTimeField(auto_now_add=True)),
                ('ultima_actividad', models.DateTimeField(db_index=True)),
            ],
            options={
                'verbose_name': 'Sesión activa',
                'verbose_name_plural': 'Sesiones activas',
            },
        ),
        migrations.RunPython(
            consolidar_pedidos_pendientes_duplicados,
            migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name='pedido',
            constraint=models.UniqueConstraint(condition=models.Q(('eliminado', False), ('estado', 'pendiente')), fields=('sucursal_cliente',), name='pedido_pendiente_unico_por_sucursal'),
        ),
        migrations.AddField(
            model_name='eventocliente',
            name='sucursal_cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_cliente', to='pedidos.sucursalcliente'),
        ),
        migrations.AddField(
            model_name='eventocliente',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_cliente_pedidos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sesionactiva',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sesion_activa_pedidos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='eventocliente',
            index=models.Index(fields=['sucursal_cliente', '-recibido_en'], name='evento_sucursal_fecha_idx'),
        ),
    ]
