# Generated by Django 6.0.8 on 2026-09-23 15:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0012_eventocliente_sesionactiva_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportacionRetencion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('generada', 'Generada'), ('confirmada', 'Confirmada en destino'), ('invalidada', 'Invalidada por cambios')], default='generada', max_length=12)),
                ('generada_en', models.DateTimeField(auto_now_add=True)),
                ('confirmada_en', models.DateTimeField(blank=True, null=True)),
                ('archivo_local_eliminado_en', models.DateTimeField(blank=True, null=True)),
                ('desde_recepcion', models.DateTimeField()),
                ('hasta_recepcion', models.DateTimeField()),
                ('sha256_archivo', models.CharField(max_length=64)),
                ('sha256_contenido', models.CharField(max_length=64)),
                ('archivo_local', models.CharField(blank=True, max_length=500)),
                ('numero_pedidos', models.PositiveIntegerField()),
                ('numero_items', models.PositiveIntegerField()),
                ('version_formato', models.PositiveSmallIntegerField(default=1)),
                ('referencia_confirmacion', models.CharField(blank=True, max_length=120)),
            ],
            options={
                'ordering': ['-generada_en'],
            },
        ),
        migrations.AddField(
            model_name='pedido',
            name='first_received_at',
            field=models.DateTimeField(blank=True, db_index=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='eventocliente',
            name='first_received_at',
            field=models.DateTimeField(blank=True, db_index=True, editable=False, null=True),
        ),
        migrations.CreateModel(
            name='RegistroPurga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ejecutada_en', models.DateTimeField(auto_now_add=True)),
                ('motivo', models.CharField(max_length=24)),
                ('numero_pedidos', models.PositiveIntegerField()),
                ('numero_items', models.PositiveIntegerField()),
                ('numero_macropedidos', models.PositiveIntegerField()),
                ('numero_eventos', models.PositiveIntegerField(default=0)),
                ('fecha_confirmacion_min', models.DateTimeField(blank=True, null=True)),
                ('fecha_confirmacion_max', models.DateTimeField(blank=True, null=True)),
                ('exportacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purgas', to='pedidos.exportacionretencion')),
            ],
        ),
        migrations.CreateModel(
            name='PedidoEnExportacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sha256_contenido', models.CharField(max_length=64)),
                ('exportacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='miembros', to='pedidos.exportacionretencion')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exportaciones_retencion', to='pedidos.pedido')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('exportacion', 'pedido'), name='pedido_unico_por_exportacion')],
            },
        ),
        migrations.CreateModel(
            name='PedidoPurgado',
            fields=[
                ('codigo_publico', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('pedido_id_origen', models.PositiveBigIntegerField(unique=True)),
                ('motivo', models.CharField(max_length=24)),
                ('exportacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_purgados', to='pedidos.exportacionretencion')),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_purgados', to='pedidos.registropurga')),
            ],
        ),
    ]
