# Generated by Django 6.0.8 on 2026-09-24 17:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0015_mfa_estado_recuperacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='PosApiCredential',
            fields=[
                ('credential_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('edge_id', models.UUIDField(db_index=True)),
                ('token_sha256', models.CharField(editable=False, max_length=64, unique=True)),
                ('scopes', models.JSONField(default=list)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('issued_reference', models.CharField(blank=True, max_length=120)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revocation_reference', models.CharField(blank=True, max_length=120)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('rotated_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rotations', to='pedidos.posapicredential')),
                ('sucursal_cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credenciales_pos_v2', to='pedidos.sucursalcliente')),
            ],
            options={
                'indexes': [models.Index(fields=['edge_id', 'sucursal_cliente'], name='pedidos_pos_edge_id_7b1d8f_idx')],
            },
        ),
    ]
