# Generated by Django 6.0.8 on 2026-09-25 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0016_posapicredential'),
    ]

    operations = [
        migrations.AddField(
            model_name='posapicredential',
            name='pos_branch_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
