# Generated by Django 6.0.8 on 2026-09-25 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0017_pos_branch_binding'),
    ]

    operations = [
        migrations.CreateModel(
            name='PosRetentionRecovery',
            fields=[
                ('recovery_id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('edge_id', models.UUIDField(db_index=True)),
                ('pos_branch_id', models.UUIDField()),
                ('desde', models.DateTimeField()),
                ('hasta', models.DateTimeField()),
                ('old_cursor_sha256', models.CharField(max_length=64)),
                ('purge_epoch', models.CharField(max_length=64)),
                ('snapshot_sha256', models.CharField(max_length=64)),
                ('orders_sha256', models.CharField(max_length=64)),
                ('orders_count', models.PositiveIntegerField()),
                ('tombstones_sha256', models.CharField(max_length=64)),
                ('tombstones_count', models.PositiveIntegerField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de conciliación Edge'), ('intervencion_manual', 'Pérdida o discrepancia por resolver'), ('completada', 'Conciliación verificada')], default='pendiente', max_length=24)),
                ('referencia_apertura', models.CharField(max_length=120)),
                ('operador_apertura', models.CharField(max_length=64)),
                ('referencia_cierre', models.CharField(blank=True, max_length=120)),
                ('operador_cierre', models.CharField(blank=True, max_length=64)),
                ('edge_ack_sha256', models.CharField(blank=True, max_length=64)),
                ('custody_sha256', models.CharField(blank=True, max_length=64)),
                ('freeze_evidence_sha256', models.CharField(blank=True, max_length=64)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('cerrada_en', models.DateTimeField(blank=True, null=True)),
                ('sucursal_cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recuperaciones_pos_v2', to='pedidos.sucursalcliente')),
            ],
        ),
    ]
