# Generated by Django 6.0.8 on 2026-09-25 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0018_pos_retention_recovery'),
    ]

    operations = [
        migrations.AddField(
            model_name='posretentionrecovery',
            name='edge_ack_nonce',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='PosEdgeSigningKey',
            fields=[
                ('key_id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('edge_id', models.UUIDField(db_index=True)),
                ('pos_branch_id', models.UUIDField()),
                ('public_key_b64', models.CharField(max_length=43, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('issued_reference', models.CharField(max_length=120)),
                ('issued_operator', models.CharField(max_length=64)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revocation_reference', models.CharField(blank=True, max_length=120)),
                ('revoked_operator', models.CharField(blank=True, max_length=64)),
                ('sucursal_cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claves_firma_pos_v2', to='pedidos.sucursalcliente')),
            ],
        ),
        migrations.AddField(
            model_name='posretentionrecovery',
            name='edge_ack_key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recuperaciones_firmadas', to='pedidos.posedgesigningkey'),
        ),
    ]
