# Generated by Django 6.0.8 on 2026-09-26 17:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


FREEZE_SQL = """
CREATE OR REPLACE FUNCTION pedidos_recovery_v2_guard() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE
    sender_old bigint;
    sender_new bigint;
BEGIN
    IF TG_TABLE_NAME = 'pedidos_pedido' THEN
        IF TG_OP <> 'INSERT' THEN sender_old := OLD.sucursal_cliente_id; END IF;
        IF TG_OP <> 'DELETE' THEN sender_new := NEW.sucursal_cliente_id; END IF;
    ELSIF TG_TABLE_NAME = 'pedidos_itempedido' THEN
        IF TG_OP <> 'INSERT' THEN
            SELECT sucursal_cliente_id INTO sender_old FROM pedidos_pedido WHERE id = OLD.pedido_id;
        END IF;
        IF TG_OP <> 'DELETE' THEN
            SELECT sucursal_cliente_id INTO sender_new FROM pedidos_pedido WHERE id = NEW.pedido_id;
        END IF;
    ELSIF TG_TABLE_NAME = 'pedidos_pedidopurgado' THEN
        IF TG_OP <> 'INSERT' THEN sender_old := OLD.sucursal_cliente_id; END IF;
        IF TG_OP <> 'DELETE' THEN sender_new := NEW.sucursal_cliente_id; END IF;
    END IF;
    IF EXISTS (
        SELECT 1 FROM pedidos_posrecoveryv2freeze
        WHERE active AND (
            (sender_old IS NOT NULL AND sender_ids @> jsonb_build_array(sender_old)) OR
            (sender_new IS NOT NULL AND sender_ids @> jsonb_build_array(sender_new))
        )
    ) THEN
        RAISE EXCEPTION 'recovery-v2 writer freeze active' USING ERRCODE = '55000';
    END IF;
    IF TG_OP = 'DELETE' THEN RETURN OLD; END IF;
    RETURN NEW;
END;
$$;
CREATE TRIGGER pedidos_recovery_v2_pedido_guard
BEFORE INSERT OR UPDATE OR DELETE ON pedidos_pedido
FOR EACH ROW EXECUTE FUNCTION pedidos_recovery_v2_guard();
CREATE TRIGGER pedidos_recovery_v2_item_guard
BEFORE INSERT OR UPDATE OR DELETE ON pedidos_itempedido
FOR EACH ROW EXECUTE FUNCTION pedidos_recovery_v2_guard();
CREATE TRIGGER pedidos_recovery_v2_tombstone_guard
BEFORE INSERT OR UPDATE OR DELETE ON pedidos_pedidopurgado
FOR EACH ROW EXECUTE FUNCTION pedidos_recovery_v2_guard();
"""


def install_freeze_guard(apps, schema_editor):
    if schema_editor.connection.vendor == "postgresql":
        with schema_editor.connection.cursor() as cursor:
            cursor.execute(FREEZE_SQL)


def remove_freeze_guard(apps, schema_editor):
    if schema_editor.connection.vendor == "postgresql":
        with schema_editor.connection.cursor() as cursor:
            for table, name in (
                ("pedidos_pedido", "pedidos_recovery_v2_pedido_guard"),
                ("pedidos_itempedido", "pedidos_recovery_v2_item_guard"),
                ("pedidos_pedidopurgado", "pedidos_recovery_v2_tombstone_guard"),
            ):
                cursor.execute(f'DROP TRIGGER IF EXISTS {name} ON {table}')
            cursor.execute("DROP FUNCTION IF EXISTS pedidos_recovery_v2_guard()")


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0019_posretentionrecovery_edge_ack_nonce_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PosAggregatedCredential',
            fields=[
                ('credential_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('edge_id', models.UUIDField(db_index=True)),
                ('pos_branch_id', models.UUIDField()),
                ('sender_ids', models.JSONField()),
                ('token_sha256', models.CharField(max_length=64, unique=True)),
                ('scopes', models.JSONField(default=list)),
                ('active', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('issued_reference', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PosRecoveryV2SigningKey',
            fields=[
                ('key_id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(max_length=8)),
                ('edge_id', models.UUIDField()),
                ('pos_branch_id', models.UUIDField()),
                ('sender_ids', models.JSONField()),
                ('public_key_b64', models.CharField(max_length=43, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revocation_reference', models.CharField(blank=True, max_length=120)),
                ('issued_reference', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PosRecoveryV2Freeze',
            fields=[
                ('freeze_id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('sender_ids', models.JSONField()),
                ('active', models.BooleanField(default=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('reference', models.CharField(max_length=120)),
                ('end_reference', models.CharField(blank=True, max_length=120)),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('active', True)), fields=('active',), name='one_active_pos_recovery_freeze')],
            },
        ),
        migrations.CreateModel(
            name='PosRecoveryV2',
            fields=[
                ('recovery_id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('edge_id', models.UUIDField()),
                ('pos_branch_id', models.UUIDField()),
                ('sender_ids', models.JSONField()),
                ('desde', models.DateTimeField()),
                ('hasta', models.DateTimeField()),
                ('pos_prestate_sha256', models.CharField(max_length=64)),
                ('purge_epoch', models.CharField(max_length=64)),
                ('snapshot_sha256', models.CharField(max_length=64)),
                ('manifest_sha256', models.CharField(max_length=64)),
                ('orders_sha256', models.CharField(max_length=64)),
                ('tombstones_sha256', models.CharField(max_length=64)),
                ('orders_count', models.PositiveIntegerField()),
                ('tombstones_count', models.PositiveIntegerField()),
                ('estado', models.CharField(default='pendiente', max_length=24)),
                ('edge_ack_sha256', models.CharField(blank=True, max_length=64)),
                ('edge_ack_nonce', models.UUIDField(blank=True, null=True)),
                ('receipt_sha256', models.CharField(blank=True, max_length=64)),
                ('opened_reference', models.CharField(max_length=120)),
                ('closed_reference', models.CharField(blank=True, max_length=120)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('freeze', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pedidos.posrecoveryv2freeze')),
                ('edge_key', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='edge_recoveries', to='pedidos.posrecoveryv2signingkey')),
                ('pedidos_key', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pedidos.posrecoveryv2signingkey')),
            ],
        ),
        migrations.CreateModel(
            name='PosRecoveryV2Nonce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nonce', models.UUIDField()),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('recovery', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pedidos.posrecoveryv2')),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pedidos.posrecoveryv2signingkey')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('key', 'nonce'), name='unique_edge_recovery_v2_nonce')],
            },
        ),
        migrations.RunPython(install_freeze_guard, remove_freeze_guard),
    ]
