# Generated by Django 6.0.8 on 2026-09-26 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0020_aggregated_recovery_v2'),
    ]

    operations = [
        migrations.AddField(
            model_name='posrecoveryv2',
            name='recovered_orders_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='posrecoveryv2',
            name='recovered_orders_sha256',
            field=models.CharField(default='', max_length=64),
        ),
    ]
