# Generated by Django 6.0.8 on 2026-09-26 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0021_recovered_archive_proof'),
    ]

    operations = [
        migrations.AddField(
            model_name='posaggregatedcredential',
            name='revocation_reference',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
